/* ECAP registration + course-code storage.
   MVP: browser localStorage (same-device lookup). Upgrade path: swap these
   functions for calls to a Supabase table — nothing else needs to change.

   Code format: ECAP-<INITIALS>-<LOCATION><YYYY>-<RANDOM3>
   e.g. ECAP-AS-CN2026-7K2  (Ama Serwaa, China cohort, 2026, random suffix)
   The three cohorts run: October in China (CN), February in the UK (UK),
   June in Ghana (GH) — see ECAP_COHORTS in js/courses.js.

   Initials, location normalisation and the random suffix are generated by
   js/course-code.js (ECAPCourseCode) — load it before this file. It also
   drives the ID card renderer, so the course code shown to a participant and
   the one printed on their card are always produced the same way. */
(function (global) {
  "use strict";
  const KEY = "ecap_registrations";

  function readAll() {
    try { return JSON.parse(localStorage.getItem(KEY) || "{}"); }
    catch (e) { return {}; }
  }

  function writeAll(all) {
    try { localStorage.setItem(KEY, JSON.stringify(all)); } catch (e) { /* storage unavailable */ }
  }

  // ECAPCourseCode.getInitials() can return "" for a name it can't represent
  // in A-Z (e.g. non-Latin script with no accent-strippable equivalent) —
  // per the design brief, fall back rather than block registration.
  function safeInitials(fullName) {
    const initials = global.ECAPCourseCode.getInitials(fullName);
    return initials || "XX";
  }

  function generateCode(fullName, locationCode, year) {
    const all = readAll();
    const initials = safeInitials(fullName);
    const location = global.ECAPCourseCode.normaliseLocationCode(locationCode) || "XX";
    const yyyy = String(year);
    let code, suffix;
    do {
      suffix = global.ECAPCourseCode.createRandomSuffix();
      code = global.ECAPCourseCode.formatCourseCode({
        fullName: fullName, locationCode: location, year: yyyy, randomSuffix: suffix,
      }) || ("ECAP-" + initials + "-" + location + yyyy + "-" + suffix);
    } while (all[code]);
    return code;
  }

  function saveRegistration(record) {
    const all = readAll();
    const code = generateCode(record.fullName, record.cohortLocation, record.cohortYear);
    all[code] = Object.assign({}, record, { code: code, createdAt: new Date().toISOString() });
    writeAll(all);
    return code;
  }

  function lookupCode(code) {
    const all = readAll();
    return all[(code || "").trim().toUpperCase()] || null;
  }

  global.EcapRegistration = { generateCode, saveRegistration, lookupCode, safeInitials };
})(window);
